name: Create pull request

on:
  create

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v4
        with:
          script: |
            github.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `WIP ${GITHUB_REF#refs/heads/}`,
              body: `version: ${GITHUB_REF#refs/heads/}`,
              head: ${GITHUB_REF#refs/heads/},
              base: "main"
            })