name: Create pull request

on:
  create

jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v4
        if: ${{ startsWith(github.ref,'refs/heads') }}
        env:
          BRANCH: ${{ github.ref }}
        with:
          script: |
            github.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `WIP ${process.env.BRANCH}`,
              body: `version: ${process.env.BRANCH}`,
              head: process.env.BRANCH,
              base: "main"
            })