name: Create pull request

on:
  create

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v4
        env:
          BRANCH: ${{ GITHUB_REF#refs/heads/ }}
        with:
          script: |
            github.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `WIP ${process.env.BRANCH}`,
              body: `version: ${process.env.BRANCH}`,
              head: process.env.BRANCH,
              base: "main"
            })